# ========== TYPES ==========

type User {
  id: ID!
  email: String!
  name: String!
}

type Product {
  id: ID!
  name: String!
  description: String
  price: Float!
  stock: Int!
}

type StockResponse {
  available: Boolean!
  currentStock: Int!
}

type OrderItem {
  productId: ID!
  quantity: Int!
  unitPrice: Float!
}

type Order {
  id: ID!
  userId: ID!
  items: [OrderItem!]!
  total: Float!
  status: String!
  createdAt: String!
}

# Input speciaux pour passer des objets en parametre de mutation
input OrderItemInput {
  productId: ID!
  quantity: Int!
  unitPrice: Float!
}

# ========== QUERIES ==========

type Query {
  users: [User!]!
  user(id: ID!): User

  products: [Product!]!
  product(id: ID!): Product
  checkStock(productId: ID!, quantity: Int!): StockResponse

  order(id: ID!): Order
  ordersByUser(userId: ID!): [Order!]!
}

# ========== MUTATIONS ==========

type Mutation {
  createUser(email: String!, name: String!, password: String!): User

  createProduct(name: String!, description: String, price: Float!, stock: Int!): Product
  updateStock(id: ID!, quantity: Int!): Product

  createOrder(userId: ID!, items: [OrderItemInput!]!): Order
  cancelOrder(id: ID!): Order
}
